### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Forrest-ht** [Andrew-Brown1/Smooth_AP#10]
could you release pretrianed model for expriment compasion? Thank you

**Comment by Andrew-Brown1** [comment]
Hi,

Sure, this will be in the next update, I will let you know when I release it

**Comment by alberto139** [comment]
Hi Andrew,

Thank you for sharing your work with us. I know you've been busy since the release of this paper and accompanying code, but I was wondering if this is still in your pipeline or if you've fully moved on from it.

Thanks!
