### ISSUE TITLE
Which GPU was used for training?

### ISSUE THREAD

**Issue by yash0307** [Andrew-Brown1/Smooth_AP#12]
Dear Andrew,

Thanks for releasing the implementation for your paper. Which GPU did you use for iNaturalist training(s)? I am unable to fit a batch of size 384 on a 32GB V100 due to memory issues.

Regards,
Yash Patel.

**Comment by Andrew-Brown1** [comment]
Hey Yash, 

So I used a Quadro RTX 8000 ;) 

Smooth-AP still achieves good results with smaller batch sizes as well that could fit on 32GB.

Andrew B

**Comment by yash0307** [comment]
Thanks for the prompt response.
