### ISSUE TITLE
lr_scheduler

### ISSUE THREAD

**Issue by interestingzhuo** [Andrew-Brown1/Smooth_AP#13]
torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=opt.tau, gamma=opt.gamma)

The default opt.tau is not a list of increasing integers? when I run the code with the default setting, I will get the following error.

Traceback (most recent call last):
  File "main.py", line 210, in <module>
    scheduler    = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=opt.tau, gamma=opt.gamma)
  File "/workdir/wangzhiling02/conda/envs/DL/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 242, in __init__
    ' increasing integers. Got {}', milestones)
ValueError: ('Milestones should be a list of increasing integers. Got {}', [200, 300, 300, 120, 220, 250, 280])

**Comment by Andrew-Brown1** [comment]
Hi, 

Thank you for noting this, it should be [200, 300]
