### ISSUE TITLE
Code when number of samples per class is not fixed

### ISSUE THREAD

**Issue by elias-ramzi** [Andrew-Brown1/Smooth_AP#14]
Hi,
Thank you for the repository.

Did you implemented a version of the SmoothAP that would take as input the prediction and their labels ? 
For cases when the number of samples per class is not fixed.

For instance for the SOP sampling.

Thanks,
Elias

**Comment by Andrew-Brown1** [comment]
Hey Elias,

Great question. No I did not implement this version of SmoothAP. It is non-trivial to write the tensor manipulations in the loss computation when each class has different numbers of samples. But perhaps I will get time soon to make it more flexible like you say.

**Comment by elias-ramzi** [comment]
Hi,
I closed the issue because I managed to implement a general version of your SmoothAP. I am not sure it is the best way but it seems to work.
When you have time I could share it with you if you want !

**Comment by Andrew-Brown1** [comment]
Oh Cool! 

Yeah I'd love to see that, is it in a repo that you have public?

**Comment by elias-ramzi** [comment]
Not yet, I will fork your repo and push the modified version. I will add some comments because some modifications are a little bit artificial

**Comment by elias-ramzi** [comment]
Here : https://github.com/elias-ramzi/Smooth_AP/blob/general_smooth_ap/src/losses.py
I also added a test
