### ISSUE TITLE
Hyper-params for the competing methods.

### ISSUE THREAD

**Issue by yash0307** [Andrew-Brown1/Smooth_AP#16]
Dear Authors,

As you are the first ones to show DML results on iNaturalist dataset, I want to ask if the backbone and embedding size for the competition methods is the same for Smooth AP?

Thank you.

Regards,
Yash Patel.

**Comment by Andrew-Brown1** [comment]
Hey, 
If I am remembering correctly, the competition methods are testing long tailed classification, so it was not relevant for us to use the same backbone or embedding as those methods, as we are not comparing to them. 
I don't know what backbone and embedding sizes competition participants used
