### ISSUE TITLE
Hyper parameters for INaturalist

### ISSUE THREAD

**Issue by elias-ramzi** [Andrew-Brown1/Smooth_AP#17]
Hi,

Could you share the hyper-parameters used for the training on INaturalist ?
Specifically the command we can use, as you shared for the VehicleID dataset (`python main.py --fc_lr_mul 1 --bs 384`).

Thanks,
Elias

**Comment by Andrew-Brown1** [comment]
Hey, 

I think it was: python main.py --fc_lr_mul 2 --bs 384 --dataset Inaturalist
