### ISSUE TITLE
Online Hard Negative Mining

### ISSUE THREAD

**Issue by Zen3515** [Andrew-Brown1/Smooth_AP#18]
I saw that you have used it for SOP, but I couldn't find the implementation in the code.

Could you guide me on how you implemented it?

**Comment by Andrew-Brown1** [comment]
We used the same implementation of hard negative mining as [5]. This implementation can be found in their repo: https://github.com/kunhe/Deep-Metric-Learning-Baselines/blob/master/datasets.py#L230

Specifically, the dataset class "SuperLabelTrainDataset" 

[5] Cakir, F., He, K., Xia, X., Kulis, B., Sclaroff, S.: Deep metric learning to rank. In: Proc. CVPR (2019)
