### ISSUE TITLE
The confusion about the loss function

### ISSUE THREAD

**Issue by curryJ** [Andrew-Brown1/Smooth_AP#21]
Thank you for  the project.
I have a confusion about the smooth-ap loss function
![image](https://user-images.githubusercontent.com/23001027/121293595-78ee0a00-c91e-11eb-8489-595f17c22ac2.png)
The input of forward process is only the features,but no class labels,so I don't know how to distinguish the positive and negative samples like the loss function in the paper. 
Thank you!

**Comment by MauritsBleeker** [comment]
https://github.com/Andrew-Brown1/Smooth_AP/blob/master/src/Smooth_AP_loss.py#L34

It is index-based!

Hope this helps

**Comment by curryJ** [comment]
> https://github.com/Andrew-Brown1/Smooth_AP/blob/master/src/Smooth_AP_loss.py#L34
> 
> It is index-based!
> 
> Hope this helps
Thank you for reply.You mean  the input data is index-based?The shape of input is [batch*feat_dims],so the positive and negative sample is separated by index?

**Comment by curryJ** [comment]
> https://github.com/Andrew-Brown1/Smooth_AP/blob/master/src/Smooth_AP_loss.py#L34
> 
> It is index-based!
> 
> Hope this helps

Thank you! I have found the parameter num_id,which is the class label!
