### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by bixiaopeng0** [Andrew-Brown1/Smooth_AP#3]
Do you try differenet batch size to influence the result and if i use small bs, will the result be terrible?

**Comment by Andrew-Brown1** [comment]
hi,
So in the ablation studies in the paper we see that larger batch sizes lead to better results using Smooth-AP (Table 5), and there is some further analysis into this in the supplementary (on arXiv version).

This does not mean though that the performance is bad with small batch sizes, and no experiments that I did showed that. I think this just means that perhaps Smooth-AP is complemented particularly well by large batch sizes.
