### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by interestingzhuo** [Andrew-Brown1/Smooth_AP#5]
Eq. 3 is wrong? maybe it should be `(si-sj)<0` to count the items whose similarity is bigger than si

**Comment by interestingzhuo** [comment]
![image](https://user-images.githubusercontent.com/43921151/92463145-fce35c00-f1fd-11ea-9ade-ef103618cf2e.png)

**Comment by WeidiXie** [comment]
yes, you are right, there is a typo here, will fix it in the next arXiv version.

**Comment by interestingzhuo** [comment]
But the code is based on Eq.3，why does it work？

**Comment by WeidiXie** [comment]
because the code is not based on eq3, it's based on eq4, meaning 1{(sj-si)>0}.

**Comment by interestingzhuo** [comment]
Thank you, I got it
